### ISSUE TITLE
update

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/io.lbry.lbry-app#1]
![captura de tela de 2017-12-12 11-03-11](https://user-images.githubusercontent.com/26097419/33885960-1c21788c-df2c-11e7-8402-8f17b51d0599.png)

**Comment by nedrichards** [comment]
patches welcome! you just need to find the new URL and update here: https://github.com/flathub/io.lbry.lbry-app/blob/master/io.lbry.lbry-app.json#L85 

then download it, and run the sha256sum tool on the file you downloaded locally. Then add the value to the file and send a PR here.

**Comment by nedrichards** [comment]
@julianrichen this looks like one for you, if @LeandroStanger can't do it ;-)

**Comment by julianrichen** [comment]
Sorry wasn't watching to this repo. I also found out today that you can subscribe to RSS feeds on Github: https://github.com/lbryio/lbry-app/releases.atom

Hopefully I won't miss it next time :)

Currently building: https://flathub.org/builds/#/builders/1/builds/1269

I realize I should have created a pull and run the `bot<comma> build`. Next time I guess.

**Comment by julianrichen** [comment]
Updated, either:
```
flatpak --user update io.lbry.lbry-app
``` 
or
```
flatpak update io.lbry.lbry-app
```

Thank you for reporting.
