### ISSUE TITLE
The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by iuyte** [flathub/io.lbry.lbry-app#10]
I'm getting the following error when running the app:
```
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: The name org.freedesktop.secrets was not provided by any .service files
```
Is anyone else having a similar issue?

This is using the latest version of the app, on Fedora Workstation 28 from a minimal install.
Flatpak version: 0.99.2

**Comment by iuyte** [comment]
Also: the home page does not load

**Comment by TingPing** [comment]
You need gnome-keyring installed on the host.

**Comment by iuyte** [comment]
Totally forgot about that, thanks.
