### ISSUE TITLE
Remove access to $HOME

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/io.lbry.lbry-app#12]
Giving LBRY access to $HOME is unnecessary, it only needs to store videos and such and it can do so perfectly fine in `./var/data`. It's worth noting that LBRY also hosts other things than videos as I've been able to test and that's a security risk which can easily be avoided.

**Comment by kcseb** [comment]
From what I can see on Line 26 (https://github.com/flathub/io.lbry.lbry-app/blob/master/io.lbry.lbry-app.json#L26), LBRY has access to Read and Write permissions but not Execute permissions.
It can download to that directory, and even read files there but not exactly execute anything maliciously. 

I don't forsee LBRY having access to $HOME being a security issue. (for the time being)

**Comment by TingPing** [comment]
> It can download to that directory, and even read files there but not exactly execute anything maliciously.

HOME access means sandbox escape, means you can do literally anything.

**Comment by kcseb** [comment]
@iuyte Since you're a bit more familiar with Flatpak than I am, would you like to shed a little light on this situation? Thank you.

**Comment by iuyte** [comment]
In the LBRY app settings, you can have a custom download directory, which I figured is why having access to $HOME is a good idea. However, we can advise users who use this to use something else. It would remain possible to have a LBRY download folder in a place $HOME/Downloads/lbry

**Comment by lionirdeadman** [comment]
@kcseb Read and write to $HOME can easily mean you can change the `.bashrc` or other similar files which would execute outside of the sandbox.

We could give access to LBRY to `$HOME/Downloads` and `$HOME/Videos` specifically instead of simply `$HOME` or we could keep it all under `.var/app/io.lbry.lbry-app`, both would be an improvement.

**Comment by kcseb** [comment]
Closed a similar issue relating to limiting FS permissions and the like. Closing this one as well. 

Limiting the file systems just isn't necessary nor practical right now.

**Comment by chpio** [comment]
> Limiting the file systems just isn't necessary

Why is it "not necessary" to not allow an app to break out of the sandbox in an obvious way?

> nor practical

What do you mean by that? Are those path somehow hardcoded? Iv tried setting it to an other location (i definitely do not want to put video files in my home dir and pay extra money for backups) that worked (`sudo flatpak override --filesystem=/data/lbry io.lbry.lbry-app` and set that dir in the settings). But when i disallow it to access my home (`sudo flatpak override --nofilesystem=home io.lbry.lbry-app`) the app just crashes on startup. With enabled access to home it still downloads *some* (?!) videos to *home/Downloads*.

**Comment by defaultpage** [comment]
> Read and write to $HOME can easily mean you can change the .bashrc or other similar files which would execute outside of the sandbox.

> Limiting the file systems just isn't necessary nor practical right now.

So, Flatpak's sandboxing is a lie.
