### ISSUE TITLE
Daemon has exited

### ISSUE THREAD

**Issue by Wetrain** [flathub/io.lbry.lbry-app#21]
I can not launch the latest lbry as i see an error saying the Daemon failed to start.

```Daemon: 2019-03-22 09:35:09,621 INFO     lbrynet.extras.daemon.Daemon:390: Platform: {
  "processor": "",
  "python_version": "3.7.1",
  "platform": "Linux-5.0.2-arch1-1-ARCH-x86_64-with-glibc2.3.4",
  "os_release": "5.0.2-arch1-1-ARCH",
  "os_system": "Linux",
  "lbrynet_version": "0.34.0",
  "lbryschema_version": "0.0.16",
  "build": "release",
  "distro": {
    "id": "org.freedesktop.platform",
    "version": "18.08",
    "version_parts": {
      "major": "18",
      "minor": "08",
      "build_number": ""
    },
    "like": "",
    "codename": "Flatpak runtime"
  },
  "desktop": "GNOME"
}

Daemon: 2019-03-22 09:35:10,384 ERROR    lbrynet.extras.daemon.Daemon:400: lbrynet API failed to bind TCP localhost:5279 for listening. Daemon is already running or this port is already in use by another application.```

**Comment by choffee** [comment]
I think this is beacuse the lbry daemon keeps running in the background after you close the main window. I assume normally it would be able to connect and restart as required but becuase the versions are completly seperate in flatpak versions it's struggling to restart the daemon from the other version.
Not sure how we can fix this in a sensible way other than having the error/solution documented.

**Comment by kcseb** [comment]
If this is still an issue on version 0.35.X, please let us know. Otherwise, close the issue. Thank you! 

(P.S. Check the startup guide... https://lbry.com/faq/startup-troubleshooting)
