### ISSUE TITLE
app fails to launch: can't mkdir parents 

### ISSUE THREAD

**Issue by rich-coe** [flathub/io.lbry.lbry-app#26]
% flatpak run io.lbry.lbry-app
bwrap: Can't mkdir parents for [$HOME]/.var/app/io.lbry.lbry-app/config/user-dirs.dirs: Read-only file system
.var/app/io.lbry.lbry-app/ exists and contains /cache /config /data

Version: 0.33.2

**Comment by kcseb** [comment]
@rich-coe Have you resolved this issue? If not... do you have any steps to reproduce or further information? 
Thanks.

**Comment by rich-coe** [comment]
No, I still have the issue.
I installed flatpak
I installed the app.
When I go to run it, I get the error.  
It looks like the dir path should be the sandbox for the app?
It's all new to me, I couldn't find anyone else with error, or why it was happening.

**Comment by kcseb** [comment]
We have recently pushed 0.35.0, please update to this version and try again. 

If the issue persists, I'll forward this to the team.
