### ISSUE TITLE
Merge Access to Repository, please. 

### ISSUE THREAD

**Issue by kcseb** [flathub/io.lbry.lbry-app#30]
This isn't an issue with the application per se, but I would like to request access to merge PRs to master. I am one of the maintainers for the LBRY app on Linux (Arch Linux, specifically.)

It would make maintaining this repository much easier if I had merge access so I wouldn't have to wait around for someone else who has it.

@tzarebczan Can verify that I am a trustworthy individual for this. 

I do believe @TingPing is the owner of this repository, or at least has the rights to make the reqested role changes. (If not, I do apologise for tagging you...)

Thank you.

**Comment by TingPing** [comment]
This package doesn't seem poorly maintained but I suppose it can't hurt.

If you are involved upstream I'd for them to get involved more. For example the appdata file should not exist here and should be upstream.

Anyway invite sent.
