### ISSUE TITLE
Last update (0.38.0) won't start

### ISSUE THREAD

**Issue by jkonecny12** [flathub/io.lbry.lbry-app#45]
**Describe the bug**
I'm using LBRY from Flatpak for some time now but after last update I can't start LBRY. 

```
$ flatpak run io.lbry.lbry-app
/app/bin/lbry-app: line 2: /app/lbry-app/lbry-app: No such file or directory
```

I tried to ``install --reinstall`` and ``remove`` & ``install`` still the same issue.
I'm using Fedora 31:

```
$ uname -a
Linux loki.packetseekers 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ flatpak --version
Flatpak 1.4.3
```

**To Reproduce**
1. Update to newest version.
2. flatpak run io.lbry.lbry-app

**Expected behavior**
The LBRY app should start as expected.

**Desktop (please complete the following information):**
 - OS: Linux  - Fedora
 - Version - 31

**Comment by jbal91** [comment]
As a workaround, you can use the command `flatpak run --command=/app/lbry-app/lbry io.lbry.lbry-app`.

**Comment by jkonecny12** [comment]
Thanks a lot for the workaround!

**Comment by kcseb** [comment]
This has been fixed. 
Ref: [49](https://github.com/flathub/io.lbry.lbry-app/pull/49)

Please allow time for this to update on Flathub.org then update from there.

**Comment by jkonecny12** [comment]
Thanks a lot for this update.

Yes it works, however, not quite right for some reason.

I'm able to start LBRY by ``flatpak run io.lbry.lbry-app`` but for some reason it does not work when I use start from desktop. It does nothing. If you need some debug logs, I'll try to provide them.

**Comment by jkonecny12** [comment]
Ahh, newest version (updated today) works like a charm.

Thanks a lot for your work!!! I will send you LBC if you will give me your wallet.
