### ISSUE TITLE
Please update to 0.38.2

### ISSUE THREAD

**Issue by jkonecny12** [flathub/io.lbry.lbry-app#46]
There is a new version 0.38.2 released, could you please update flatpak to get the new version.

https://github.com/lbryio/lbry-desktop/releases/

Thanks for packaging this!

**Comment by kcseb** [comment]
Right now, there are some changes to the package (on LBRY's end, themselves) that have caused us some issues in regards to building. 

Currently, there is a workaround that has been posted in another [issue](https://github.com/flathub/io.lbry.lbry-app/issues/45). 

`flatpak run --command=/app/lbry-app/lbry io.lbry.lbry-app`

I'm going to go ahead and close this issue for right now. I'll likely have to downgrade the entire repository back to the latest working version...
