### ISSUE TITLE
Flatpak version open another process even if it's already running

### ISSUE THREAD

**Issue by REIS0** [flathub/io.lbry.lbry-app#63]
**Bug**
lbry desktop loads another instance even though is already running

![image](https://user-images.githubusercontent.com/38042161/77657909-daba9200-6f6d-11ea-9a46-2b7c796ec5b1.png)

![image](https://user-images.githubusercontent.com/38042161/77658110-210ff100-6f6e-11ea-9d9e-6c1cc9d8d0dd.png)

**To Reproduce**
1. Open lbry
2. Close
3. Open lbry lauching from other source besides the system tray
4. Now there's two lbry process running

**Expected behavior**
To open the already running lbry

**System Configuration**

- LBRY Daemon version: 0.63
- LBRY App version: 0.43.4 from Flatpak
- LBRY Installation ID:  4y64Q5nBxKmo866GngPfXHkA6HDN53s5cD3bswhpfue3HtXoZk58AnJcs1fLDnqgPi
- Operating system: Pop_OS! 19.10

**Additional context**
Originally the issue in the lbry desktop repo, reposting here.

**Comment by kcseb** [comment]
Willing to throw some LBC to whomever can take a look at this further and provide a fix!*

*Implying there is something that actually is requiring a fix, and this isn't just a one-off issue. Thanks!

**Comment by TingPing** [comment]
Usually applications throw a lock file in `/tmp` which won't work. A random test:

Close all instances and run this multiple times:

`flatpak run --env=TMPDIR=/var/tmp io.lbry.lbry-app`

And see if it raises existing instances.

**Comment by REIS0** [comment]
Apparently is exactly as @TingPing said, using this method does not spawn more than one instance

![image](https://user-images.githubusercontent.com/38042161/78298998-09fb7100-7523-11ea-9a21-4a332c6650b1.png)

**Comment by kcseb** [comment]
So, what would we need to do to get this into the mainstream? That way you don't have to run the app via the above command _every time_.

**Comment by corecontingency** [comment]
@kcseb 

I made a pull request [here](https://github.com/flathub/io.lbry.lbry-app/pull/77) for fixing just this issue.

A separate pull request [here](https://github.com/flathub/io.lbry.lbry-app/pull/78) has my other changes, which includes updating `Electron`, `libnotify`, and `libsecret`.

Tagging you because I noticed that you aren't watching this repository.
