### ISSUE TITLE
Version 0.45 build failed

### ISSUE THREAD

**Issue by Zlopez** [flathub/io.lbry.lbry-app#67]
**Describe the bug**
Looking at the [CI output for last commit](https://flathub.org/builds/#/builders/10/builds/2197), it looks like build for `0.45` failed and the officially available version on Flathub is still `0.44`.

**Comment by kcseb** [comment]
Pretty sure this was due to an absolutely tiny casing change I made to the icon name during a test that I, like a numpty, forgot to revert. It _should_ be back to normal now with the latest patch. Thanks for this!

**Comment by kcseb** [comment]
Can confirm latest build (0.45.1) is up and running with **SUCCESS**. 

Ref: https://flathub.org/builds/#/builders/32/builds/19589

Closing.
