### ISSUE TITLE
Deb File Update Prompt On Flatpak Version [BUG]

### ISSUE THREAD

**Issue by natealx** [flathub/io.lbry.lbry-app#69]
**Describe the bug**
The update prompts the user to update via a deb file and leaves the application with a persistent footer bar that won't go away even if on the latest flatpak version.

**To Reproduce**
If there is a deb file update it will prompt you for a update.

**Expected behavior**
Have the prompt reflect a flatpak update is available and or the ability to hide the footer bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/64503107/81223807-297c3280-8fd6-11ea-9936-79b1a7b38cfc.png)

**Desktop**
 - OS: Manjaro 20
 - Flatpak from Flathub
 - Version 0.44.0

**Additional context**
If you attempt to update via the deb file on manjaro the update fails.

**Comment by kcseb** [comment]
This would be something under the control of the @LBRY app developers... Not us that deal with the Flatpak. 

I've pushed the latest update to the Flathub a few days ago and you should update from that or install via `flatpak install flathub io.lbry.lbry-app`. 

The Flatpak uses the latest `.deb` file for it's updates, so this shouldn't continually prompt you to update _after_ updating. Try closing the entire LBRY app (daemon too) and see if it persists.
