### ISSUE TITLE
App fails to launch on .desktop entry

### ISSUE THREAD

**Issue by temrix** [flathub/io.lbry.lbry-app#85]
**Describe the bug**
With #82 being merged, I only tested with `flatpak --user run io.lbry.lbry-app`. However the `.desktop` file needs to be adjusted too.

Line 61: `"find usr/share/applications/ -name 'lbry.desktop' -type f -exec sed -i 's|/.*/.*/lbry|/app/lbry-app/lbry-app|i' {} \\;",` probably needs to include `zypak-wrapper` but I am not familiar enough with `sed` to do it myself.

**To Reproduce**
Click on LBRY desktop icon.

**Expected behavior**
The application should launch.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - DE: GNOME

**Comment by kcseb** [comment]
@ProfessorDey is the one who brought the `sed` command in, to begin with. He's going to be working on the [code-testing](https://github.com/flathub/io.lbry.lbry-app/tree/code-testing) branch. 

If you two could collaborate a bit (help each other test, when builds succeed), it would be great. 

Once a working build is produced, I'll merge the PR and get it going out to the upstream!

**Comment by ProfessorDey** [comment]
@temrix If you could give that branch a test, that's be appreciated, I don't have a machine I can do so on myself, at least not readily. The script already includes the required wrapper but when I replaced the sed previously I overlooked the /app/bin/ folder as the proper thing to be referencing as it worked fine directing straight to the binary itself.

**Comment by temrix** [comment]
The build now works. Thank you!
