### ISSUE TITLE
update freedesktop runtime to 20.08

### ISSUE THREAD

**Issue by eszlari** [flathub/io.lbry.lbry-app#88]

**Comment by kcseb** [comment]
Will get `freedesktop` updated to the latest version on the next application patch from LBRY Inc. Thanks!

**Comment by eszlari** [comment]
The build failed, because you didn't bump the BaseApp version to 20.08 too.

**Comment by kcseb** [comment]
Yep - Sorry, fixed that. Was in a rush yesterday and tried cramming the update into my schedule. 

Should be all good now. https://flathub.org/builds/#/builders/19/builds/4060
