### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Zahrun** [flathub/io.lbry.lbry-app#98]
New version released 15 days ago

**Comment by jkonecny12** [comment]
Do the maintainer want a help with this project? I'm happy to help.

**Comment by adam-stambaugh** [comment]
A new version (v0.52.0) is out.

**Comment by jkonecny12** [comment]
There is already update PR created: https://github.com/flathub/io.lbry.lbry-app/pull/103

**Comment by hfiguiere** [comment]
pr #103 was merged.
